# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'kube-manifests'
    Contents: '**'  # Optionally, specify file patterns
    TargetFolder: '$(Build.ArtifactStagingDirectory)/kube-manifests'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/kube-manifests'
    ArtifactName: 'kube-manifests'

